
export Auth0_Domain='manualdev.us.auth0.com'
export ALGORITHMS=['RS256']
export API_AUDIENCE='rainforest-api'
export CLIENT_ID='EySnHcxJQ5fYy1a9ZTwoFfMjnR9x97KI'
# add staff and owner token
# tokens only here for testing will be in .env or heroku vars for a typical application
export STAFF_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFyZmxmUEY2T0JwR2hobkprbzViVSJ9.eyJpc3MiOiJodHRwczovL21hbnVhbGRldi51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjFhOTVjNDA2ZDkyNGEwMDc4NTA3M2M2IiwiYXVkIjoicmFpbmZvcmVzdC1hcGkiLCJpYXQiOjE2Mzg5NDIwMjYsImV4cCI6MTYzOTAxNDAyNiwiYXpwIjoiRXlTbkhjeEpRNWZZeTFhOVpUd29GZk1qblI5eDk3S0kiLCJzY29wZSI6IiIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTpvcmRlcl9pdGVtcyIsImRlbGV0ZTpvcmRlcnMiLCJkZWxldGU6dXNlcnMiLCJnZXQ6b3JkZXJfaXRlbXMiLCJnZXQ6b3JkZXJzIiwiZ2V0OnVzZXJzIiwicGF0Y2g6b3JkZXJfaXRlbXMiLCJwb3N0Om9yZGVyX2l0ZW1zIiwicG9zdDpvcmRlcnMiLCJwb3N0OnVzZXJzIl19.CXBA9Y-yqZIpeQD_dm8hHv_eupyp7wNg5j_FGwwap9fOumOewn0q9ocBkf2DaU5AcbUWtQSs9AZM81hmhLDLz-yVj5RJjqSQOEEzauiNJVuZW_fF_NePJUJkvYeaXmNW8NizAyiZ1IXso_edjtPWoCSjrbE1nW4rpg1UQAY2ntnnSV3phdbiXUPnRbZklaDP6Ly5RI6efR_mUhYgvCevnE0kpwWh5GXGbe1-S5TqjU4Zn2Y1KWY4wz_GprWD2run309yMsBzJTPF6V0-tkdnRDo4FZ3zF7gaP-z0kETfC5XB5Vn-CgPa_B5tyh9RiGcYYV7z3N5Sr2QrOPQD0E_b8Q
export OWNER_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFyZmxmUEY2T0JwR2hobkprbzViVSJ9.eyJpc3MiOiJodHRwczovL21hbnVhbGRldi51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjFhOTViNjQyMTEyNzUwMDcxNTlkZTg0IiwiYXVkIjoicmFpbmZvcmVzdC1hcGkiLCJpYXQiOjE2Mzg5NDE4NTQsImV4cCI6MTYzOTAxMzg1NCwiYXpwIjoiRXlTbkhjeEpRNWZZeTFhOVpUd29GZk1qblI5eDk3S0kiLCJzY29wZSI6IiIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTpvcmRlcl9pdGVtcyIsImRlbGV0ZTpvcmRlcnMiLCJkZWxldGU6cHJvZHVjdHMiLCJkZWxldGU6dXNlcnMiLCJnZXQ6b3JkZXJfaXRlbXMiLCJnZXQ6b3JkZXJzIiwiZ2V0OnVzZXJzIiwicGF0Y2g6b3JkZXJfaXRlbXMiLCJwYXRjaDpwcm9kdWN0cyIsInBvc3Q6b3JkZXJfaXRlbXMiLCJwb3N0Om9yZGVycyIsInBvc3Q6cHJvZHVjdHMiLCJwb3N0OnVzZXJzIl19.Hp6-UmKkaR80TWY0bF1NgnNvqhV3HAN22Chlr0Md94tS5wKCewCmjuPHDAKopfIesyj5IUANNgTRVl7h8kJy09fAV11uqpiKo3GfM8TxtnDSRrgIdoAryg_wwFxqSRk2nFsOtHZZH5iHEivPSPVgGtXBNHLNIGOE1pLLoMVdP0uwNh53n-THFp_ueYYC3hlGyNjXVeVekKhp_D8GnJg0hW7yWmuyjHkCI4tvsJuaAACqrC2QXNgyrFqpbvRIm6xnNk1m9JguDvwIsRA5nUOywfTehDrtQCKXoR4CvEXLMR9dC7qmIZTIMZsV3GCKBQe_67bO_3hnkUnplk3CThwW6A

#local 
export FLASK_APP='rainforest.app'
export FLASK_ENV='development'
export FLASK_DEBUG=true

#local testing
export DATABASE_NAME='rainforest_db'
export DATABASE_USERNAME="user"
export DATABASE_USER_PASSWORD="pass"

fix_url="postgresql://${DATABASE_USERNAME}:${DATABASE_USER_PASSWORD}@localhost:5432/${DATABASE_NAME}"

export DATABASE_URL_FIXED=$fix_url

